Rework initial explanation of shape tree structure and model
shapetrees/specification pull request #44
Opened 2021-05-03 13:55 UTC by justinwb

2021-05-31 16:36 UTC, ericprud requested changes

2021-05-31 16:36 UTC, ericprud commented on index.bs
> +    have exactly one node which conforms to [=shape=] `SH`.
PROPOSE: s/MUST have/has/

2021-05-31 16:36 UTC, ericprud commented on index.bs
> +A [=shape tree locator=] includes one or more [=shape tree locations=] via
I'm tempted to table-ify these definitions to make the list boundaries clear:

## Location properties

property | definition
-- | --
`st:node` | identifies the focus node for [=shape=] validation in the associated [=managed resource=]
`st:shape` | identifies the [=shape=] to which `st:node` must conform
`st:hasShapeTree` | the [=shape tree=] defining this [=shape tree instance=]
`st:hasRootShapeTree` | marks the primary, or parent [=shape tree=] in a physical hierarchy, and is set by the [Plant Operation](#plant-shapetree).
`st:hasShapeTreeInstanceRoot` | marks the primary, or parent [=shape tree instance=] in a physical hierarchy, and is set by the [Plant Operation](#plant-shapetree). <span class="note">@@ define as parm to PLANT?</span>

Note that A [=shape tree root=], and its corresponding [=shape tree instance root=] can be planted within an existing managed hierarchy, alongside or within other [=shape tree roots=] and [=shape tree instance roots=].
Properties like [=Shape tree locations=] in a given [=shape tree locators=] may have different focus nodes.

2021-05-31 22:14 UTC, justinwb commented on index.bs
> +
> a server-managed Resource that enumerates nested resources

A container resource isn't completely server-managed though, just the containment triples.

2021-06-01 15:19 UTC, ericprud commented
for parallel-ism, propose s/st:hasShapeTreeInstanceRoot/st:hasRootShapeTreeInstance/

2021-06-01 18:06 UTC, justinwb commented
> for parallel-ism, propose s/st:hasShapeTreeInstanceRoot/st:hasRootShapeTreeInstance/

Okay - made this change under the operations refactor branch to save another branch merge - https://github.com/shapetrees/specification/pull/45/commits/03e63e9a8a71fa2dbe0a64873328f4b0bd63799a

2021-06-03 12:48 UTC, ericprud approved these changes

2021-06-03 17:30 UTC, merged